blogs/urls.py
from django.urls import path

from . import views

app_name = 'blogs'
urlpatterns = [
    # List of blogs urls
    path('', views.blog_list_view, name='list'),
    path('author/<slug:author_username>/', views.blog_list_view, name='author_list'),
    path('category/<slug:category_slug>/', views.blog_list_view, name='category'),

    # CRUD urls
    path('create/', views.BlogCreateView.as_view(), name='create'),
    path('detail/<slug:slug>/', views.BlogDetailView.as_view(), name='detail'),
    path('update/<slug:slug>/', views.BlogUpdateView.as_view(), name='update'),
    path('delete/<slug:slug>/', views.BlogDeleteView.as_view(), name='delete'),

    # Author & Admin urls
    path('my-blogs/', views.BlogAuthorProfileView.as_view(), name='author'),
    path('review/', views.BlogReviewView.as_view(), name='review'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pages.urls')),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('allauth.urls')),
    path('comments/', include('comments.urls')),
    path('blogs/', include('blogs.urls')),
    path('rosetta/', include('rosetta.urls'))
]

# urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blogs/models.py
from django.db import models
from django.db.models import Avg
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from django.contrib.auth import get_user_model
from django.utils.html import format_html


class BlogManager(models.Manager):
    def published(self):
        return self.filter(status='p')


class Blog(models.Model):
    STATUS_CHOICES = (
        ('d', _("Draft")),
        ('p', _("Public")),
        ('r', _("Review")),
    )

    class Meta:
        ordering = ['-datetime_modified']
        verbose_name = _("Blog")
        verbose_name_plural = _("Blogs")
        permissions = [
            ('publish_blog', 'Can publish blog'),
        ]

    title = models.CharField(_('Title'), max_length=100)
    slug = models.SlugField(_("Slug"), unique=True)
    content = models.TextField(_('Content'), )
    categories = models.ManyToManyField('categories.Category', related_name='blogs', verbose_name=_("Categories"))
    cover = models.ImageField(_('Cover'), upload_to='covers/')
    author = models.ForeignKey(get_user_model(), on_delete=models.CASCADE, related_name='blogs',
                               verbose_name=_("Author"))
    status = models.CharField(_("Status"), max_length=1, choices=STATUS_CHOICES)
    is_vip = models.BooleanField(_("Vip blog"), default=False)
    hits = models.ManyToManyField('accounts.IpAddress', related_name='blogs', through='BlogIp', verbose_name=_("Hits"))
    datetime_created = models.DateTimeField(auto_now_add=True)
    datetime_modified = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blogs:detail', kwargs={'slug': self.slug})

    def cover_tag(self):
        return format_html(
            f"<img width=65 height=65 style='object-fit: contain; border-radius:3px' src='{self.cover.url}'>")

    cover_tag.short_description = _('Cover')

    @property
    def avg_score(self):
        scores = self.comments.filter(is_active=True).aggregate(Avg('score'))
        if not scores['score__avg']:
            return 0
        return scores['score__avg']

    @property
    def total_hits(self):
        return self.hits.all().count()

    objects = BlogManager()


class BlogIp(models.Model):
    blog = models.ForeignKey('blogs.Blog', on_delete=models.CASCADE)
    ip = models.ForeignKey('accounts.IpAddress', on_delete=models.CASCADE)
    datetime_created = models.DateTimeField(auto_now_add=True)

blogs/forms.py
from django import forms
from django.utils.translation import gettext_lazy as _
from django.contrib.auth import get_user_model

from .models import Blog


class BlogForm(forms.ModelForm):
    class Meta:
        model = Blog
        fields = ['title', 'slug', 'content', 'categories', 'cover', 'is_vip', 'status', 'author']
        widgets = {
            'title': forms.TextInput(attrs={'placeholder': _('Title'), 'class': 'form-control'}),
            'slug': forms.TextInput(attrs={'placeholder': _('Slug'), 'class': 'form-control'}),
            'content': forms.Textarea(attrs={'placeholder': _('content'), 'rows': 5, 'class': 'form-control'}),
            'categories': forms.SelectMultiple(attrs={'style': 'height:150px;'})
        }

    def __init__(self, *args, **kwargs):
        user = kwargs.pop('user')
        super().__init__(*args, **kwargs)
        self.fields['author'].queryset = get_user_model().objects.filter(groups__name__in=['author'])
        if not user.is_superuser:
            self.fields.pop('author')
            self.fields['status'].choices = [
                ('d', _("Draft")),
                ('r', _("Review")),
            ]

blogs/views.py
from django.contrib.auth.mixins import PermissionRequiredMixin, UserPassesTestMixin
from django.shortcuts import get_object_or_404, redirect, render
from django.core.exceptions import BadRequest, PermissionDenied
from django.contrib.auth import get_user_model
from django.core.paginator import Paginator
from django.urls import reverse_lazy
from django.views import generic

from .models import Blog
from .forms import BlogForm
from categories.models import Category
from .mixins import BlogFormFieldsMixin, BlogIpMixin, CreateUpdateFormValidMixin


def blog_list_view(request, author_username=None, category_slug=None):
    # Variables
    query = request.GET.get('q', '')
    page = request.GET.get('page', '1')
    author_name = None
    category_obj = None

    # Queries
    if author_username:
        author = get_object_or_404(get_user_model(), username=author_username)
        blogs = author.blogs.published()
        author_name = author.get_full_name() if author.get_full_name() else author.username
    elif category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        blogs = category.blogs.published()
        category_obj = category
    else:
        blogs = Blog.objects.published()

    # Pagination
    paginator = Paginator(blogs.filter(title__icontains=query), 5)
    blogs = paginator.page(page)
    page_range = paginator.get_elided_page_range(page, on_each_side=2, on_ends=1)

    # Context
    context = {
        'query': query,
        'blogs': blogs,
        'page_range': page_range,
        'author_name': author_name,
        'category_obj': category_obj,
    }
    return render(request, 'blogs/list.html', context=context)


class BlogDetailView(UserPassesTestMixin, BlogIpMixin, generic.DetailView):
    def test_func(self):
        blog = self.get_object()
        user = self.request.user
        return blog.status == 'p' or blog.author == user or user.has_perm('blogs.publish_blog')

    model = Blog
    context_object_name = 'blog'
    template_name = 'blogs/detail.html'


class BlogCreateView(PermissionRequiredMixin, CreateUpdateFormValidMixin, BlogFormFieldsMixin, generic.CreateView):
    model = Blog
    form_class = BlogForm
    template_name = 'blogs/create.html'
    permission_required = 'blogs.add_blog'


class BlogUpdateView(UserPassesTestMixin, CreateUpdateFormValidMixin, PermissionRequiredMixin, BlogFormFieldsMixin,
                     generic.UpdateView):
    def test_func(self):
        blog = self.get_object()
        user = self.request.user
        return blog.author == user and blog.status == 'd' or user.is_superuser

    model = Blog
    form_class = BlogForm
    template_name = 'blogs/create.html'
    permission_required = 'blogs.change_blog'


class BlogDeleteView(PermissionRequiredMixin, generic.DeleteView):
    model = Blog
    permission_required = "blogs.delete_blog"
    success_url = reverse_lazy('blogs:list')
    template_name = 'blogs/delete.html'


class BlogAuthorProfileView(PermissionRequiredMixin, generic.ListView):
    model = Blog
    paginate_by = 10
    context_object_name = 'blogs'
    template_name = 'blogs/author_blogs.html'
    permission_required = 'blogs.add_blog'

    def get_queryset(self):
        return Blog.objects.filter(author=self.request.user)


class BlogReviewView(PermissionRequiredMixin, generic.ListView):
    model = Blog
    paginate_by = 10
    context_object_name = 'blogs'
    template_name = 'blogs/review.html'
    permission_required = 'blogs.publish_blog'

    def get_queryset(self):
        return Blog.objects.filter(status='r')

    def post(self, request, *args, **kwargs):
        blog = get_object_or_404(Blog, pk=request.POST.get('blog_id'))
        if blog.status == 'r':
            if '1' in request.POST:
                blog.status = 'p'
            elif '0' in request.POST:
                blog.status = 'd'
            else:
                raise BadRequest('Bad request')
            blog.save()
            return redirect('blogs:review')
        raise PermissionDenied()

templates/blogs/author_blogs.html
{% extends '_base.html' %}
{% load blog_tags %}
{% load static %}

{% block header %}
    <h1 class="page-title wow fadeInUp delay-0-2s">مقالات من</h1>
{% endblock %}


{% block right-sidebar %}
    {% include 'partial/pages/dashboard_sidebar.html' %}
{% endblock %}

{% block content %}
    <table class="table table-striped">
        <thead>
        <tr>
            <th scope="col">ردیف</th>
            <th scope="col">عنوان</th>
            <th scope="col">تصویر</th>
            <th scope="col">وضعیت</th>
        </tr>
        </thead>
        <tbody>
        {% for blog in blogs %}
            <tr>
                <th scope="row">{{ forloop.counter }}</th>
                <td><a href="{{ blog.get_absolute_url }}"><b>{{ blog.title }}</b></a></td>
                <td><img src="{{ blog.cover.url }}" style="height: 50px; width: 50px; object-fit: contain"
                         alt="{{ blog.title }}"></td>
                <td>
                    {% if blog.status == 'p' %}
                        <small class="badge-success p-1 rounded">منتشر شده</small>
                    {% elif blog.status == 'd' %}
                        <small class="badge-danger p-1 rounded">پیش نویس</small>
                        <small class="badge-warning p-1 rounded"><a href="{% url 'blogs:update' blog.slug %}">ویرایش</a></small>
                    {% else %}
                        <small class="badge-info p-1 rounded">در حال بررسی</small>

                    {% endif %}
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <div class="d-block">
        {% if page_obj.has_other_pages %}
            <div class="text-center mt-25 justify-content-center mb-5">
                {% if page_obj.has_previous %}
                    <a href="?page={{ page_obj.previous_page_number }}" class="sub-title p-2 rounded"><i
                            class="fa fa-angle-double-right"></i></a>
                {% endif %}
                <span class="sub-title p-2">{{ page_obj.start_index }} تا {{ page_obj.end_index }}</span>
                {% if page_obj.has_next %}
                    <a href="?page={{ page_obj.next_page_number }}" class="sub-title p-2 rounded"><i
                            class="fa fa-angle-double-left"></i></a>
                {% endif %}
            </div>
        {% endif %}
    </div>
{% endblock %}

templates/blogs/create.html
{% extends "_base.html" %}

{% block header %}
    <h1 class="page-title wow fadeInUp delay-0-2s">افزودن مقاله جدید</h1>
{% endblock %}


{% block right-sidebar %}
    {% include 'partial/pages/dashboard_sidebar.html' %}
{% endblock %}

{% block content %}
    <form id="contact-page-form" class="contact-form-three pt-20 wow fadeInUp delay-0-2s"
          method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <h3 class="comment-title mb-40">مقاله جدید</h3>
        <div class="row clearfix">
            <div class="col-sm-6 form-group">
                {{ form.title }}
            </div>
            <div class="col-sm-6 form-group">
                {{ form.slug }}
                <span class="text text-danger">{{ form.slug.errors }}</span>
            </div>
            <div class="col-md-12 form-group">
                {{ form.content }}
            </div>
            <div class="col-sm-6 form-group">
                {{ form.categories }}
            </div>
            <div class="col-sm-6 form-group">
                {{ form.cover }}
            </div>
            <div class="col-sm-6 form-group">
                <label for="id_status">{{ form.status.label }}</label>
                {{ form.status }}
                <span class="text-danger">{{ form.status.errors|striptags }}</span>
            </div>
            <div class="col-sm-6 form-group">
                <label for="id_is_vip">{{ form.is_vip.label }}</label>
                <p> آیا یک مقاله ویژه است؟ {{ form.is_vip }}</p>
            </div>
            {% if user.is_superuser %}
                <div class="col-sm-6 form-group">
                    <label for="id_author">{{ form.author.label }}</label>
                    {{ form.author }}
                </div>
            {% endif %}
            <div class="col-md-12">
                <div class="form-group mb-0">
                    <button class="theme-btn" type="submit">ذخیره <i class="fas fa-arrow-left"></i></button>
                </div>
            </div>
        </div>
    </form>
{% endblock %}

templates/blogs/delete.html
{% extends "_base.html" %}

{% block body %}
    <form method="post">
        {% csrf_token %}
        <p>Are you sure you want to delete "{{ blog }}"?</p>
        {{ form }}
        <input type="submit" value="Yes">
    </form>
{% endblock %}

templates/blogs/detail.html
{% extends '_base.html' %}
{% load comments_tags %}
{% load humanize %}
{% load static %}
{% load gravatar %}
{% load jalali_tags %}

{% block header %}
    <h1 class="page-title wow fadeInUp delay-0-2s">مقاله ی "{{ blog.title }}"</h1>
{% endblock %}

{% block left-sidebar %}
    {% include 'partial/pages/sidebar.html' %}
{% endblock %}

{% block content %}
    {% if not blog.is_vip or blog.is_vip and perms.accounts.can_see_vip or  blog.author == user %}
        <div class="blog-details-content rmb-75">
            <div class="blog-standard-item">
                <img src="{{ blog.cover.url }}" class="blog-cover" alt="Blog">
                <ul class="blog-meta">
                    <li><i class="far fa-calendar-alt"></i> <a href="blog-details.html">{{ blog.datetime_modified|to_jalali:'%Y/%m/%d' }}</a>
                    </li>
                    <li><i class="far fa-comments"></i> <a href="#comments">نظرات ({{ blog.comments.active.count }})</a>
                    </li>
                    <li><i class="far fa-eye"></i> <a href="#">بازدید کنندگان ({{ blog.total_hits }})</a></li>
                </ul>
                <h2>{{ blog.title }}</h2>
                <p>{{ blog.content|linebreaks }}</p>
                <div class="blog-footer d-flex flex-wrap align-items-center pt-25">
                    <div class="tags mb-10 mr-auto">
                        <b>Tags </b>
                        {% for category in blog.categories.active %}
                            <a href="{{ category.get_absolute_url }}">{{ category.title }}</a>
                        {% endfor %}

                    </div>
                    <div class="social mb-10">
                        <b>Share: </b>
                        <a href="http://facebook.com"><i class="fab fa-facebook-f"></i></a>
                        <a href="http://twitter.com"><i class="fab fa-twitter"></i></a>
                        <a href="https://www.instagram.com/"><i class="fab fa-instagram"></i></a>
                    </div>
                </div>
            </div>

            <div class="comment-item admin-comment p-40 text-white bg-blue mb-75 wow fadeInUp delay-0-2s">
                <div class="author-image">
                    {% gravatar blog.author.email %}
                </div>
                <div class="comment-details">
                    <h3>{{ blog.author.get_full_name|default:blog.author }}</h3>
                    <p>{{ blog.author.bio|default:'زندگی نامه ای ثبت نشده است' }}</p>
                    <div class="social mt-15">
                        <a href="#"><i class="fab fa-facebook-f"></i></a>
                        <a href="#"><i class="fab fa-twitter"></i></a>
                        <a href="#"><i class="fab fa-instagram"></i></a>
                        <a href="#"><i class="fab fa-behance"></i></a>
                        <a href="#"><i class="fab fa-dribbble"></i></a>
                    </div>
                </div>
            </div>

            {% if blog.status == 'p' %}
                {% blog_comments %}
            {% endif %}
        </div>
    {% else %}
        <div class="blog-details-content rmb-75">
            <div class="blog-standard-item">
                <p class="text-center sub-title w-100" style="font-size: 20px">این یک مقاله ویژه است. برای مشاهده کامل
                    آن ابتدا <a href="{% url 'account_subscription' %}">اشتراک</a> ما را خریداری نمایید.</p>
            </div>
        </div>
    {% endif %}
{% endblock %}

{% block JS %}
    <!--====== Comment Js ======-->
    <script src="{% static 'local/js/comment.js' %}"></script>
    <!--====== Nice Select ======-->
    <script src="{% static 'assets/js/jquery.nice-select.min.js' %}"></script>
{% endblock %}

templates/blogs/list.html
{% extends '_base.html' %}
{% load static %}
{% load jalali_tags %}

{% block header %}
    {% if request.resolver_match.url_name == 'list' %}
        <h1 class="page-title wow fadeInUp delay-0-2s">مقالات ما</h1>
    {% elif request.resolver_match.url_name == 'category' %}
        <h1 class="page-title wow fadeInUp delay-0-2s">دسته بندی " {{ category_obj.title }} "</h1>
    {% elif request.resolver_match.url_name == 'author_list' %}
        <h1 class="page-title wow fadeInUp delay-0-2s">مقالات " {{ author_name }} "</h1>
    {% endif %}

    {% if query %}
        <p class="breadcrumb-item text-light h2">نتایج جستجو برای "{{ query }}" </p>
    {% endif %}
{% endblock %}

{% block left-sidebar %}
    {% include 'partial/pages/sidebar.html' %}
{% endblock %}

{% block content %}
    {% for blog in blogs %}
        <div class="blog-standard-item wow fadeInUp delay-0-2s">
            <img src="{{ blog.cover.url }}" class="blog-cover" alt="Blog">
            <ul class="blog-meta">
                <li><i class="far fa-calendar-alt"></i> <span>{{ blog.datetime_modified|to_jalali:'%d %B %Y' }}</span>
                </li>
                <li><i class="far fa-comments"></i> <span>نظرات ({{ blog.comments.active.count }})</span></li>
                <li><i class="far fa-eye"></i> <span>بازدید کنندگان ({{ blog.total_hits }})</span></li>
            </ul>
            <h2 class="d-inline ml-2"><a href="{{ blog.get_absolute_url }}">{{ blog.title }}</a></h2>
            {% if blog.is_vip %}<b class="badge-danger px-2 rounded">مقاله ویژه</b>{% endif %}
            <p> {{ blog.content|truncatewords:20 }} </p>
            <a href="{{ blog.get_absolute_url }}" class="theme-btn">بیشتر بخوانید<i class="fas fa-arrow-left"></i></a>
        </div>
    {% empty %}
        <p class="sub-title text-center w-100">هیچ مقاله ای وجود ندارد</p>
    {% endfor %}
{% endblock %}

{% block pages %}
    <div class="d-block">
        {% if blogs.has_other_pages %}
            <div class="page-number mt-25 justify-content-center mb-5">
                {% if blogs.has_previous %}
                    <a href="?page=1&q={{ query }}"><i class="fa fa-angle-double-right"></i></a>
                {% endif %}
                {% for i in page_range %}
                    {% if i == blogs.number %}
                        <span class="active">{{ i }}</span>
                    {% elif i == paginator.ELLIPSIS %}
                        <span>{{ i }}</span>
                    {% else %}
                        <a href="?page={{ i }}&q={{ query }}">{{ i }}</a>
                    {% endif %}
                {% endfor %}
                {% if blogs.has_next %}
                    <a href="?page={{ blogs.paginator.num_pages }}&q={{ query }}"><i
                            class="fa fa-angle-double-left"></i></a>
                {% endif %}
            </div>
        {% endif %}
    </div>
{% endblock %}

templates/blogs/review.html
{% extends '_base.html' %}
{% load blog_tags %}
{% load static %}

{% block header %}
    <h1 class="page-title wow fadeInUp delay-0-2s">بررسی مقالات</h1>
{% endblock %}

{% block right-sidebar %}
    {% include 'partial/pages/dashboard_sidebar.html' %}
{% endblock %}

{% block content %}
    <table class="table table-striped">
        <thead>
        <tr>
            <th scope="col">ردیف</th>
            <th scope="col">عنوان</th>
            <th scope="col">نویسنده</th>
            <th scope="col">تصویر</th>
            <th scope="col">وضعیت</th>
        </tr>
        </thead>
        <tbody>
        {% for blog in blogs %}
            <tr>
                <th scope="row">{{ forloop.counter }}</th>
                <td><a href="{{ blog.get_absolute_url }}"><b>{{ blog.title }}</b></a></td>
                <td>{{ blog.author }}</td>
                <td><img src="{{ blog.cover.url }}" style="height: 50px; width: 50px; object-fit: contain"
                         alt="{{ blog.title }}"></td>
                <td>
                    <form action="{% url 'blogs:review' %}" method="post">
                        {% csrf_token %}
                        <input type="hidden" name="blog_id" value="{{ blog.id }}">
                        <button class="alert-danger rounded px-1" type="submit" name="0">رد صلاحیت</button>
                        <button class="alert-success rounded px-1" type="submit" name="1">منتشر شود</button>
                    </form>
                </td>
            </tr>
        {% empty %}
            <td colspan="5">
                <p class="alert-success text-center">تبریک میگم. هیچ مقاله ای برای بررسی وجود ندارد</p>
            </td>
        {% endfor %}
        </tbody>
    </table>

    <div class="d-block">
        {% if page_obj.has_other_pages %}
            <div class="text-center mt-25 justify-content-center mb-5">
                {% if page_obj.has_previous %}
                    <a href="?page={{ page_obj.previous_page_number }}" class="sub-title p-2 rounded"><i
                            class="fa fa-angle-double-right"></i></a>
                {% endif %}
                <span class="sub-title p-2">{{ page_obj.start_index }} تا {{ page_obj.end_index }}</span>
                {% if page_obj.has_next %}
                    <a href="?page={{ page_obj.next_page_number }}" class="sub-title p-2 rounded"><i
                            class="fa fa-angle-double-left"></i></a>
                {% endif %}
            </div>
        {% endif %}
    </div>
{% endblock %}