blogs/urls.py
from django.urls import path

from . import views

app_name = 'blogs'
urlpatterns = [
    # List of blogs urls
    path('', views.blog_list_view, name='list'),
    path('author/<slug:author_username>/', views.blog_list_view, name='author_list'),
    path('category/<slug:category_slug>/', views.blog_list_view, name='category'),

    # CRUD urls
    path('create/', views.BlogCreateView.as_view(), name='create'),
    path('detail/<slug:slug>/', views.BlogDetailView.as_view(), name='detail'),
    path('update/<slug:slug>/', views.BlogUpdateView.as_view(), name='update'),
    path('delete/<slug:slug>/', views.BlogDeleteView.as_view(), name='delete'),

    # Author & Admin urls
    path('my-blogs/', views.BlogAuthorProfileView.as_view(), name='author'),
    path('review/', views.BlogReviewView.as_view(), name='review'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pages.urls')),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('allauth.urls')),
    path('comments/', include('comments.urls')),
    path('blogs/', include('blogs.urls')),
    path('rosetta/', include('rosetta.urls'))
]

# urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pages/urls.py
from django.urls import path

from . import views

app_name = 'pages'
urlpatterns = [
    path('', views.home_view, name='home'),
    path('contact/', views.contact_view, name='contact'),
]

blogs/models.py
from django.db import models
from django.db.models import Avg
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from django.contrib.auth import get_user_model
from django.utils.html import format_html


class BlogManager(models.Manager):
    def published(self):
        return self.filter(status='p')


class Blog(models.Model):
    STATUS_CHOICES = (
        ('d', _("Draft")),
        ('p', _("Public")),
        ('r', _("Review")),
    )

    class Meta:
        ordering = ['-datetime_modified']
        verbose_name = _("Blog")
        verbose_name_plural = _("Blogs")
        permissions = [
            ('publish_blog', 'Can publish blog'),
        ]

    title = models.CharField(_('Title'), max_length=100)
    slug = models.SlugField(_("Slug"), unique=True)
    content = models.TextField(_('Content'), )
    categories = models.ManyToManyField('categories.Category', related_name='blogs', verbose_name=_("Categories"))
    cover = models.ImageField(_('Cover'), upload_to='covers/')
    author = models.ForeignKey(get_user_model(), on_delete=models.CASCADE, related_name='blogs',
                               verbose_name=_("Author"))
    status = models.CharField(_("Status"), max_length=1, choices=STATUS_CHOICES)
    is_vip = models.BooleanField(_("Vip blog"), default=False)
    hits = models.ManyToManyField('accounts.IpAddress', related_name='blogs', through='BlogIp', verbose_name=_("Hits"))
    datetime_created = models.DateTimeField(auto_now_add=True)
    datetime_modified = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blogs:detail', kwargs={'slug': self.slug})

    def cover_tag(self):
        return format_html(
            f"<img width=65 height=65 style='object-fit: contain; border-radius:3px' src='{self.cover.url}'>")

    cover_tag.short_description = _('Cover')

    @property
    def avg_score(self):
        scores = self.comments.filter(is_active=True).aggregate(Avg('score'))
        if not scores['score__avg']:
            return 0
        return scores['score__avg']

    @property
    def total_hits(self):
        return self.hits.all().count()

    objects = BlogManager()


class BlogIp(models.Model):
    blog = models.ForeignKey('blogs.Blog', on_delete=models.CASCADE)
    ip = models.ForeignKey('accounts.IpAddress', on_delete=models.CASCADE)
    datetime_created = models.DateTimeField(auto_now_add=True)

templates/partial/pages/dashboard_sidebar.html
<div class="col-xl-4 col-lg-5">
    <div class="service-sidebar rmb-75">
        <div class="service-widget service-list wow fadeInUp delay-0-3s"
             style="visibility: visible; animation-name: fadeInUp;">
            <ul>
                <li {% if request.resolver_match.url_name == 'account_profile' %}class="active"{% endif %}><a
                        href="{% url 'account_profile' %}">مشخصات من<i class="fas fa-angle-left"></i></a></li>
                <li {% if request.resolver_match.url_name == 'account_subscription' %}class="active"{% endif %}>
                    <a href="{% url 'account_subscription' %}">اشتراک من<i class="fas fa-angle-left"></i></a></li>

                {% if perms.blogs.add_blog %}
                    <li {% if request.resolver_match.url_name == 'create' %}class="active"{% endif %}><a
                            href="{% url 'blogs:create' %}">افزودن مقاله<i class="fas fa-angle-left"></i></a></li>
                    <li {% if request.resolver_match.url_name == 'author' %}class="active"{% endif %}><a
                            href="{% url 'blogs:author' %}">مقالات من <i class="fas fa-angle-left"></i></a></li>
                {% endif %}
                {% if perms.blogs.publish_blog %}
                    <li {% if request.resolver_match.url_name == 'review' %}class="active"{% endif %}><a
                            href="{% url 'blogs:review' %}">بررسی مقالات <i class="fas fa-angle-left"></i></a></li>
                {% endif %}
                <li><a href="{% url 'account_logout' %}" class="text-danger">خروج از حساب<i
                        class="fas fa-angle-left"></i></a>
                </li>
            </ul>
        </div>
    </div>
</div>

templates/partial/pages/errors.html
{% if form.errors %}
    {% for field in form %}
        {% for error in field.errors %}
            <p class="alert alert-danger">{{ error|striptags }}</p>
        {% endfor %}
    {% endfor %}
{% endif %}

templates/partial/pages/footer.html
{% load static %}

<footer class="footer-section bg-lighter rel z-1 pt-50 mt-50">
    <div class="container">

        <div class="row justify-content-between">
            <div class="col-xl-3 col-sm-6 col-7 col-small">
                <div class="footer-widget about-widget">
                    <div class="footer-logo mb-20">
                        <a href="index.html"><img src="{% static 'assets/images/logos/logo.png' %}" alt="Logo"></a>
                    </div>
                    <p>AKLog یه پروژه ابتدایی برا محک زدن توانایی های خود و برای روزمه خود ساخته و توسعه یافته است</p>
                    <a href="" class="read-more">مشاهده کامل <i class="fas fa-arrow-left"></i></a>
                </div>
            </div>
            <div class="col-xl-2 col-sm-4 col-5 col-small">
                <div class="footer-widget link-widget">
                    <h4 class="footer-title">دسترسی سریع</h4>
                    <ul class="list-style-two">
                        <li><a href="{% url 'pages:home' %}">خانه</a></li>
                        <li><a href="{% url 'account_profile' %}">پروفایل</a></li>
                        <li><a href="{% url 'blogs:list' %}">لیست مقالات</a></li>
                        <li><a href="{% url 'pages:contact' %}">تماس با ما</a></li>
                    </ul>
                </div>
            </div>
            <div class="col-xl-3 col-md-4">
                <div class="footer-widget contact-widget">
                    <h4 class="footer-title">در تماس باشید</h4>
                    <ul class="list-style-three">
                        <li><i class="fas fa-map-marker-alt"></i> :/</li>
                        <li><i class="fas fa-envelope-open"></i>
                            <a href="mailto:discord.1843@gmail.com">discord.1843@gmail.com</a>
                        </li>
                        <li><i class="fas fa-phone"></i><a dir="ltr" href="callto:+989999999">+98 (999) 9999</a>
                        </li>
                    </ul>
                    <div class="social-style-one mt-25">
                        <a href="#"><i class="fab fa-facebook-f"></i></a>
                        <a href="#"><i class="fab fa-twitter"></i></a>
                        <a href="#"><i class="fab fa-linkedin-in"></i></a>
                        <a href="#"><i class="fab fa-instagram"></i></a>
                    </div>
                </div>
            </div>
        </div>
        <div class="copyright-area text-center">
            <p>© 2022 <a href="index.html">Sland.</a> All rights reserved</p>
        </div>
    </div>
    <img class="dots-shape" src="{% static 'assets/images/shapes/dots.png' %}" alt="Shape">
    <img class="tringle-shape" src="{% static 'assets/images/shapes/tringle-two.png' %}" alt="Shape">
    <img class="close-shape" src="{% static 'assets/images/shapes/close.png' %}" alt="Shape">
    <img class="circle-shape" src="{% static 'assets/images/shapes/circle-two.png' %}" alt="Shape">
    <div class="left-circles"></div>
    <div class="right-circles"></div>
</footer>

templates/partial/pages/messages.html
{% if messages %}
    {% for message in messages %}
        <div class=" rounded mb-1 p-10 text">
        <p class="alert-{{ message.tags }} text-center p-2 h4">{{ message }}</p>
    </div>
    {% endfor %}
{% endif %}

templates/partial/pages/navbar.html
{% load static %}

<!--Header-Upper-->
<div class="header-upper bg-white">
    <div class="container clearfix">
        <div class="header-inner py-20 border-bottom-0">
            <div class="logo-outer">
                <div class="logo"><a href="{% url 'pages:home' %}">
                    <img class="main-logo" src="{% static 'assets/images/logos/logo.png' %}" alt="Logo"></a>
                </div>
            </div>

            <div class="nav-outer clearfix">
                <!-- Main Menu -->
                <nav class="main-menu navbar-expand-lg">
                    <div class="navbar-header">
                        <div class="logo-mobile"><a href="{% url 'pages:home' %}"><img
                                class="main-logo"
                                src="{% static 'assets/images/logos/logo.png' %}"
                                alt="Logo"></a>
                            <a href="{% url 'account_profile' %}" class="r-0">حساب کاربری</a>
                        </div>

                        <!-- Toggle Button -->
                        <button type="button" class="navbar-toggle" data-toggle="collapse"
                                data-target=".navbar-collapse" aria-controls="main-menu">
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>

                    </div>

                    <div class="navbar-collapse collapse clearfix" id="main-menu">
                        <ul class="navigation clearfix">
                            <li class=""><a href="{% url 'blogs:list' %}">خانه</a></li>
                            <li class="dropdown"><a href="#">دسته بندی ها</a>
                                <ul>
                                    {% for category in categories %}
                                        <li><a href="{{ category.get_absolute_url }}">{{ category.title }}</a></li>
                                    {% endfor %}
                                </ul>
                            </li>
                            <li class="dropdown"><a href="#">نویسندگان</a>
                                <ul>
                                    {% for author in authors %}
                                        <li>
                                            <a href="{% url 'blogs:author_list' author.username %}">{{ author.get_short_name|default:author.username }}</a>
                                        </li>
                                    {% endfor %}
                                </ul>
                            </li>
                            <li><a href="{% url 'pages:contact' %}">تماس با ما</a></li>
                        </ul>
                    </div>
                </nav>
                <!-- Main Menu End-->
            </div>

            <!-- Main Menu End-->
            <!-- Menu Serch Box-->
            <div class="nav-search">
                <button class="fa fa-search"></button>
                <form action="{% url 'blogs:list' %}" class="hide">
                    <input type="text" placeholder="جستجو..." class="searchbox" name="q">
                    <button type="submit" class="searchbutton fa fa-search"></button>
                </form>
            </div>

            <div class="main-menu navbar-expand-lg menu-right d-none d-lg-flex align-items-center mr-lg-auto">
                {% if user.is_authenticated %}
                    <div class="navbar-collapse collapse clearfix" id="main-menu">
                        <ul class="navigation clearfix">

                            <li class="dropdown"><a href="#"><i
                                    class="ml-3 fa fa-user"></i>{{ user.get_short_name|default:user.username }}</a>
                                <ul>
                                    <li><a href="{% url 'account_profile' %}">پروفایل من</a></li>
                                    <li><a href="{% url 'account_change_password' %}">تغییر رمز عبور</a></li>
                                    <li><a class="text text-danger" href="{% url 'account_logout' %}">خروج از حساب</a>
                                    </li>
                                </ul>
                            </li>

                        </ul>
                    </div>
                {% else %}
                    <a href="{% url 'account_signup' %}" class="login"><i class="fas fa-lock"></i> ثبت نام </a>
                    <a href="{% url 'account_login' %}" class="theme-btn style-two">ورود<i
                            class="fas fa-arrow-left"></i></a>
                {% endif %}
            </div>
        </div>
    </div>
</div>
<!--End Header Upper-->

templates/partial/pages/sidebar.html
{% load blog_tags %}
{% load static %}


<div class="col-lg-4 col-md-8">
    <div class="blog-sidebar">
        {% if request.resolver_match.url_name != 'detail' %}
            <div class="widget search-widget wow fadeInUp delay-0-2s">
                <h3 class="widget-title">جستجو</h3>
                <form action="" method="get">
                    <input type="search" placeholder="جستجو..." required name="q">
                    <button type="submit"><i class="fas fa-search"></i></button>
                </form>
            </div>
        {% endif %}
        <div class="widget category-widget wow fadeInUp delay-0-4s">
            {% if request.resolver_match.url_name == 'category' and category_obj.children.active %}
                <div class="widget tag-widget wow fadeInUp delay-0-2s">
                    <h3 class="widget-title">تگ های مربوط به " {{ category_obj.title }} "</h3>
                    <div class="tag-clouds">
                        {% for child in category_obj.children.active %}
                            <a href="{% url  'blogs:category' child.slug %}">{{ child.title }}</a>
                        {% endfor %}

                    </div>
                </div>

            {% endif %}
            <!--====== Most popular blog ======-->
            {% best_blogs %}
            <!--====== Top month blogs ======-->
            {% top_month_blogs %}

            <div class="widget call-action-widget wow fadeInUp delay-0-2s">
                <h3>در هر ساعتی از شبانه روز</h3>
                <span class="h2">خوابیم :)</span>
                <div class="action-btn"><a href="{% url 'pages:contact' %}" class="theme-btn">تماس با ما<i
                        class="fas fa-arrow-left"></i></a></div>
                <div>
                    <p class="text-light h5">آدرس ایمیل ما: </p>
                    <a class="number" href="mailto:+01234567899">discord.1843@gmail.com</a>
                </div>
                <div>
                    <p class="text-light h5">شماره تماس ما: </p>
                    <a class="number d-block" dir="ltr" href="tel:+98999999999">+98 999 9999</a>
                </div>
                <img class="action-man" src="{% static 'assets/images/cover/love2.svg' %}"
                     alt="Call To Action">
                <img class="dots-shape slideUpDown"
                     src="{% static 'assets/images/shapes/white-dots-two.png' %}"
                     alt="Shape">
                <img class="circle-shape slideUpRight" src="{% static 'assets/images/shapes/circle.png' %}"
                     alt="Shape">
            </div>

        </div>
    </div>
</div>