blogs/urls.py
from django.urls import path

from . import views

app_name = 'blogs'
urlpatterns = [
    # List of blogs urls
    path('', views.blog_list_view, name='list'),
    path('author/<slug:author_username>/', views.blog_list_view, name='author_list'),
    path('category/<slug:category_slug>/', views.blog_list_view, name='category'),

    # CRUD urls
    path('create/', views.BlogCreateView.as_view(), name='create'),
    path('detail/<slug:slug>/', views.BlogDetailView.as_view(), name='detail'),
    path('update/<slug:slug>/', views.BlogUpdateView.as_view(), name='update'),
    path('delete/<slug:slug>/', views.BlogDeleteView.as_view(), name='delete'),

    # Author & Admin urls
    path('my-blogs/', views.BlogAuthorProfileView.as_view(), name='author'),
    path('review/', views.BlogReviewView.as_view(), name='review'),
]

comments/urls.py
from django.urls import path

from . import views

app_name = 'comments'
urlpatterns = [
    path('create/<slug:slug>/', views.CommentCreate.as_view(), name='create'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pages.urls')),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('allauth.urls')),
    path('comments/', include('comments.urls')),
    path('blogs/', include('blogs.urls')),
    path('rosetta/', include('rosetta.urls'))
]

# urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

comments/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _
from django.core.validators import MaxValueValidator, MinValueValidator


class CommentManager(models.Manager):
    def active(self):
        return self.filter(is_active=True)


class Comment(models.Model):
    SCORE_CHOICES = (
        (1, _("Very bad")),
        (2, _("Bad")),
        (3, _("Normal")),
        (4, _("Good")),
        (5, _("Very good")),
    )
    text = models.TextField(_('Text'))
    name = models.CharField(_('Full name'), max_length=50)
    email = models.EmailField(_("Email"))
    blog = models.ForeignKey('blogs.Blog', on_delete=models.CASCADE, related_name='comments', verbose_name=_('Blog'))
    is_active = models.BooleanField(_("Is active"), default=True)
    score = models.IntegerField(_("Score"), default=3, choices=SCORE_CHOICES,
                                validators=[MaxValueValidator(5), MinValueValidator(1)])
    parent = models.ForeignKey('self', on_delete=models.CASCADE, related_name='children', blank=True, null=True)
    datetime_created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'Commented by {self.name} on {self.blog}'

    class Meta:
        ordering = ['-datetime_created']

    objects = CommentManager()

comments/forms.py
from django import forms
from django.utils.translation import gettext_lazy as _

from .models import Comment


class CommentForm(forms.ModelForm):
    parent = forms.IntegerField(widget=forms.HiddenInput(), required=False)

    class Meta:
        model = Comment
        fields = ['name', 'email', 'text', 'score']
        widgets = {
            'name': forms.TextInput(attrs={'placeholder': _('Full name'), 'class': 'form-control'}),
            'email': forms.EmailInput(attrs={'placeholder': _('Your email'), 'class': 'form-control'}),
            'score': forms.Select(attrs={'class': 'form-group nice-select'}),
            'text': forms.Textarea(attrs={'placeholder': _('Write your message'), 'class': 'form-control', 'rows': 5}),
        }

    def __init__(self, *args, **kwargs):
        user = kwargs.pop('user')
        super().__init__(*args, **kwargs)
        if user.is_authenticated:
            self.fields.pop('name')
            self.fields.pop('email')

comments/views.py
from django.shortcuts import get_object_or_404, redirect
from django.views import generic

from .models import Comment
from .forms import CommentForm
from blogs.models import Blog


class CommentCreate(generic.CreateView):
    model = Comment
    form_class = CommentForm

    def get_form_kwargs(self):
        kwargs = super(CommentCreate, self).get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs

    def form_valid(self, form):
        blog = get_object_or_404(Blog, slug=self.kwargs['slug'])
        comment = form.save(commit=False)

        # parent comment
        parent_id = form.cleaned_data['parent']
        if parent_id:
            parent_comment = get_object_or_404(Comment, pk=parent_id)
            if not parent_comment.parent:
                comment.parent = parent_comment

        if self.request.user.is_authenticated:
            comment.name = self.request.user.username
            comment.email = self.request.user.email
        comment.blog = blog
        comment.save()

        return redirect('blogs:detail', self.kwargs['slug'])

templates/partial/comments/comments.html
{% load static %}
{% load gravatar %}
{% load humanize %}

<form id="comment-form" class="contact-form-three pt-20 wow fadeInUp delay-0-2s"
      action="{% url 'comments:create' slug %}" method="post">
    <h3 id="form-title" class="comment-title mb-40">نظر خود را بنویسید</h3>
    <p id="reply-to" class="d-none"><span id="reply-text"></span><a id="close-reply"><i
            class="far fa-window-close mx-1 text-danger"></i></a></p>
    {% csrf_token %}
    {{ form.parent }}
    <div class="row clearfix">
        {% if not user.is_authenticated %}
            <div class="col-sm-6">
                <div class="form-group">
                    {{ form.name }}
                </div>
            </div>
            <div class="col-sm-6">
                {{ form.score }}
            </div>
            <div class="col-sm-12">
                <div class="form-group">
                    {{ form.email }}
                </div>
            </div>
        {% else %}
            <div class="col-sm-12">
                {{ form.score }}
            </div>
        {% endif %}
        <div class="col-md-12">
            <div class="form-group">
                {{ form.text }}
            </div>
        </div>
        <div class="col-md-12">
            <div class="form-group mb-0">
                <button class="theme-btn" type="submit">ارسال نظر <i class="fas fa-arrow-left"></i></button>
            </div>
        </div>
    </div>
</form>
<hr>

<div class="comments mr-xl-4">
    <h3 class="comment-title pt-30 mb-40">نظرات شما</h3>
    {% for comment in comments %}
        <div class="comment-item wow fadeInUp delay-0-2s">
            <div class="author-image">
                {% gravatar comment.email 100 %}
            </div>
            <div class="comment-details">
                <div class="name-date">
                    <h4>{{ comment.name }}</h4>
                    <span class="date">{{ comment.datetime_created|naturaltime }}</span>
                </div>
                <p>{{ comment.text }}</p>
                <a class="reply" data-id="{{ comment.id }}" data-name="{{ comment.username }}">پاسخ <i
                        class="fas fa-long-arrow-alt-left"></i></a>
            </div>
        </div>
        {% for child in comment.children.active %}
            <div class="comment-item child-comment wow fadeInUp delay-0-4s">
                <div class="author-image">
                    {% gravatar child.email 100 %}
                </div>
                <div class="comment-details">
                    <div class="name-date">
                        <h4>{{ child.name }}</h4>
                        <span class="date">{{ child.datetime_created|naturaltime }}</span>
                    </div>
                    <p>{{ child.text }}</p>
                </div>
            </div>
        {% endfor %}
    {% empty %}
        <span class="sub-title w-100 text-center align-items-center">هیج نظری وجود ندارد :(</span>
    {% endfor %}
</div>